project:
  type: website
  output-dir: docs

book:
  title: "巫雨洋的学习日记"
  author: "Yuyang Wu"
  date: "2023/1/26"
  chapters:
    - test.qmd

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual


